### ISSUE TITLE
Remove 'cppfront' Subfolder and Use FetchContent for `cppfront` Dependency instead

### ISSUE THREAD

**Issue by shemeshg** [modern-cmake/cppfront#142]
I'd like to propose removing the 'cppfront' subfolder from the project. This change would allow users to independently manage the `cppfront` version that the project refers to, without being tied to the project's updates.

Instead, let's adjust the `FetchContent` example to include the `GIT_REPOSITORY` for `cppfront`  and  `cppfront-cmake` that will demonstrate how to link between them

- or maybe it is none issue since we can always `add_subdirectory(cppfront)` and change sub_directory branch

**Comment by alexreinking** [comment]
I just updated master to the latest `cppfront`.

I'm quite hesitant to use FetchContent. I don't like requiring an internet connection during the build.
