### ISSUE TITLE
[BUG] CI complain about missing standard module interface for Windows build

### ISSUE THREAD

**Issue by filipsajdak** [modern-cmake/cppfront#68]
Some tests are failing due to the following error:
```
cpp2util.h(48): fatal error C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup?
```

**Comment by alexreinking** [comment]
Thanks for opening this issue... I have not had a chance to look at this.

**Comment by alexreinking** [comment]
@JohelEGP -- do you have any idea why this is happening? It used to work, then became intermittent, and now is consistently failing.

**Comment by JohelEGP** [comment]
I suppose it's the `pure2` tests that are failing because they're trying to use C++ modules.
I can't find platform-specific flags, so perhaps it's missing one of the advertised ones at <https://github.com/hsutter/cppfront#how-do-i-build-cppfront>.

**Comment by alexreinking** [comment]
> so perhaps it's missing one of the advertised ones

No, unfortunately it's not so simple. Here's one of the command lines from the tests:

> ```
> C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\HostX64\x64\cl.exe  /nologo /TP  -external:ID:\a\cppfront\cppfront\_local\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD /experimental:module /showIncludes /FoCMakeFiles\test-case.dir\_cppfront\pure2-bounds-safety-span.cpp.obj /FdCMakeFiles\test-case.dir\ /FS -c D:\a\cppfront\cppfront\build\regression-tests\pure2-bounds-safety-span\build\_cppfront\pure2-bounds-safety-span.cpp
> ```

I can clearly see both `-std:c++20` and `/EHsc` in there.

**Comment by alexreinking** [comment]
Ugh, I wish I knew why that wasn't _always_ needed. We can try adding that.

**Comment by alexreinking** [comment]
> It seems like it's already added

Oh, and sure enough, it's in the command line above... maybe _removing_ it would help, if the MSVC version is new enough?

**Comment by JohelEGP** [comment]
Another difference is that <https://github.com/hsutter/cppfront/blob/main/regression-tests/test-results/msvc-2022/run-tests-msvc-2022.bat>
uses `-std:c++latest`.

**Comment by JohelEGP** [comment]
I don't think that's it. It still fails: <https://compiler-explorer.com/z/aGaj5z58q>.

**Comment by JohelEGP** [comment]
See <https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1011?view=msvc-170>.

**Comment by JohelEGP** [comment]
Maybe you can downgrade the version of MSVC to one that works: <https://github.com/ilammy/msvc-dev-cmd#inputs>.

**Comment by alexreinking** [comment]
This is no longer _the_ issue with MSVC. Now we have issues in the `build/check` tests
